# Lista de bairros
bairros = [
    "248",
    "Acampamento",
    "Aero Clube",
    "Assuncao",
    "Aterrado",
    "Açude II",
    "Açude III",
    "Açude IV",
    "Bairro de Fatima",
    "Barreira Cravo",
    "Bela Vista",
    "Belmonte",
    "Belo Horizonte",
    "Boa vista",
    "Bom Jesus",
    "Brasilandia",
    "Caieira",
    "Cailandia",
    "Califórnia da barra",
    "Candelaria",
    "Casa de Pedra",
    "Caviana",
    "Cidade Nova",
    "Conforto",
    "Coqueiros",
    "Divineia",
    "Dom Bosco",
    "Duzentos e Quarenta e nove",
    "Eucaliptal",
    "Fazendinha",
    "Ilha Parque",
    "Ipe Amarelo",
    "Jardi CAROLINE",
    "Jardi ESPERANCA",
    "Jardi EUROPA",
    "Jardi GUANABARA",
    "Jardi MARIANA",
    "Jardi PRIMAVERA",
    "Jardi REDENTOR",
    "Jardi SUICA",
    "Jardi VENEZA",
    "Jardim Amalia I",
    "Jardim Amalia II",
    "Jardim Belvedere",
    "Jardim Europa",
    "Jardim Paraiba",
    "Jardim Redentor",
    "Jardim Suica",
    "Jardi Cidade do Aco",
    "Jardi Tiradentes",
    "LARANJAL",
    "Laranjal",
    "Limoeiro",
    "MANGUEIRA",
    "METALURGICO",
    "MINERLANDIA",
    "MORADA DA GRANJA",
    "MORADA DO VALE",
    "Mariana Torres",
    "Minerlandia",
    "Monte Castelo",
    "Morada do Campo",
    "Morro da Conquista",
    "NOVE DE ABRIL",
    "Niteroi",
    "Nossa Senhora das Gracas",
    "Nova Esperanca",
    "Nova Primavera",
    "PARAISO",
    "PONTE ALTA",
    "PQ DAS GRACAS",
    "Padre Josimo",
    "Parque Vitoria",
    "Parque das Ilhas",
    "Pedreira",
    "Pinto da Serra",
    "Ponte Alta",
    "RECANTO DO SOL",
    "ROD DOS METALURGICOS",
    "ROMA",
    "RUSTICO",
    "Recanto da Lagoa",
    "Retiro",
    "Roma II",
    "Rústico",
    "SAO CARLOS",
    "SAO SEBASTIAO",
    "SESSENTA",
    "SIDERVILE",
    "STA INES",
    "STA TEREZA",
    "Samoa",
    "Santa Cruz I",
    "Santa Cruz II",
    "Santa Inêz",
    "Santa Rita de Cassia",
    "Santa Rita do Zarur",
    "Santo Agostinho",
    "Sessenta",
    "Siderlandia",
    "Sideropolis",
    "SAO CRISTOVAO",
    "SAO JUDAS TADEU",
    "SAO LUCAS",
    "SAO SEBASTIAO",
    "Sao Cristovao",
    "Sao Geraldo",
    "Sao Joao",
    "Sao Joao Batista",
    "Sao Lucas",
    "Sao Luiz",
    "Sao Luiz da Barra",
    "Sao Sebastiao",
    "Tangerinal",
    "Tres Pocos",
    "VILA ELMIRA",
    "VILA STA CECILIA",
    "VILAGE STA HELENA",
    "VISTA VERDE",
    "Vale Verde",
    "Varjao",
    "Verde Vale",
    "Vila Americana",
    "Vila Brasilia",
    "Vila Elmira",
    "Vila Mury",
    "Vila Rica",
    "Vila Santa Cecilia",
    "Village Sul",
    "Voldac",
    "Agua Limpa"
]

# Remover espaços antes e depois e remover duplicatas
bairros_limpos = list(set(bairro.strip().upper() for bairro in bairros))

# Ordenar a lista limpa
bairros_ordenados = sorted(bairros_limpos)

# Salvar a lista ordenada em um arquivo de texto
with open('bairros.txt', 'w') as arquivo:
    for bairro in bairros_ordenados:
        arquivo.write(f"{bairro}\n")

print("Lista de bairros salva em 'bairros.txt'.")
